---
title: "Analysis of Palmer Penguins"
author: Your favorite colleague
format: 
  html: 
    toc: true
    theme: spacelab
    code-fold: true
    code-download: true
jupyter: python3
execute: 
  echo: true
tutorial:
  id: "quarto_intro/quarto-survey"
---

```{python}
#| label: setup
#| include: false
from palmerpenguins import load_penguins_raw, load_penguins
penguins = load_penguins()
```

## Exploring the data

The `penguins` data set comes from the palmerpenguins package. We can examine it below.

```{python}
#| echo: true
from IPython.display import display, Markdown
nrows = len(penguins)

display(Markdown(f"""
This dataset has {nrows} rows.
"""))
```



```{python}
penguins
```

### Removing missing values

The data set has some observations with missing values for body mass. We will filter those out below.

```{python}
penguins = penguins.dropna(subset=["body_mass_g"])
```

## Penguin bills

In this section of the report, we'll examine characteristics of penguin bills by species. Let's focus on only the columns of the data set that we'll need. The table of the subsetted data is shown below:

```{python}
#| echo: false
# Select the "species" and "bill" columns
species_bills = penguins.loc[:, ["species", "bill_length_mm", "bill_depth_mm"]]
species_bills
```
### Visualization

We display the distribution of the penguin bill length below.

```{python}
#| echo: false
#| warning: false
#| label: plot1
from plotnine import ggplot, aes, geom_point, geom_smooth, theme_minimal, labs, geom_histogram

plot = (
    ggplot(data=species_bills, mapping=aes(x="bill_length_mm"))
    + geom_histogram()
    + theme_minimal()
    + labs(x="Bill length (mm)")
)

plot
```
Let's examine the data with a plot. We will focus on the relationship between bill length and bill depth. 

```{python}
#| label: plot2
#| echo: false
plot = (
    ggplot(data=species_bills, mapping=aes(x="bill_length_mm", y="bill_depth_mm", color="species"))
    + geom_point()
    + geom_smooth(method="lm", se=False)
    + theme_minimal()
    + labs(
        title="Within species, longer bills are deeper",
        x="Bill length (mm)",
        y="Bill depth (mm)",
    )
)

plot
```

## Appendix

Additional materials can be found below.

### Raw data

The raw data set containing additional variables for the penguins studied, is displayed below.

```{python}
#| label: display-data
load_penguins_raw()
```
